name: Deploy develop

on: 
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Make tar archive
        run: |
            ls -l
            tar -cf studio-crm.tar.gz ./

      - name: Write key to file
        run: | 
          echo "${{ secrets.SSH_KEY }}" > ~/key
          chmod 400 ~/key

      - name: Transfer files with scp
        run: scp -rBC -i ~/key -o StrictHostKeyChecking=no $(pwd)/studio-crm.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PROJECT_FOLDER}}

      - name: Unzip archive & remove archive
        run: ssh -i ~/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'tar -xf ${{ secrets.PROJECT_FOLDER }}/studio-crm.tar.gz -C ${{ secrets.PROJECT_FOLDER }}/ && rm tar -xf ${{ secrets.PROJECT_FOLDER }}/studio-crm.tar.gz'

      - name: Restart backend service
        run: ssh -i ~/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart crm-backend'

      - name: Remove key
        run: rm ~/key
  
