name: Deploy develop

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd client && npm ci

      - name: Install global dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CI: ""
  
      - name: Upload a client Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: client_build_files
          path: client/build/
  
      - name: Upload a backend Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: server_build_files
          path: backend/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          password: ${{secrets.PASSWORD}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout develop;
            git pull;

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug
        run: ls

      - uses: actions/download-artifact@v4
        with:
          name: client_build_files
          path: ${{ secrets.PATH_CLIENT_BUILD }}

      - uses: actions/download-artifact@v4
        with:
          name: client_build_files
          path: ${{ secrets.PATH_BACKEND_BUILD }}
