name: Deploy production

on: 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Install dependencies
        run: npm ci

      - name: Build project client
        run: npm run build_client

      - name: Upload a client Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: client_build_files
          path: client/build

      - name: Upload a server Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: server_build_files
          path: backend
  
