name: Deploy develop

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd client && npm ci

      - name: Install global dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CI: ""
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload a client Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: client_build_files
          path: client/build/

      - name: Upload a backend Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: server_build_files
          path: backend/dist/

  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Debug
        run: |
          pwd
          ls

      - uses: actions/download-artifact@v4
        with:
          name: client_build_files
          path: ${{ secrets.PATH_CLIENT_BUILD }}

      - uses: actions/download-artifact@v4
        with:
          name: client_build_files
          path: ${{ secrets.PATH_BACKEND_BUILD }}
