name: Deploy develop

on: 
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Write key to file
        run: | 
          echo "${{ secrets.SSH_KEY }}" > ~/key
          chmod 400 ~/key
          ls -l ~/
          pwd
          ls

      - name: Transfer files with scp
        run: scp -rBC -i ~/key -o StrictHostKeyChecking=no studio-crm ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PROJECT_FOLDER}}

      - name: Restart backend service
        run: ssh -i ~/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart crm-backend'

      - name: Remove key
        run: rm ~/key
