name: Deploy develop

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd client && npm ci

      - name: Build project
        run: npm run build

deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Upload a client Build Artifact
      uses: actions/upload-artifact@v4.3.2
      with:
        server: ${{ secrets.ADDRESS }}
        username: ${{ secrets.USERNAME }}
        passowrd: ${{ secrets.PASSWORD }}
        name: client_build_files
        path: client/build

    - name: Upload a backend Build Artifact
      uses: actions/upload-artifact@v4.3.2
      with:
        server: ${{ secrets.ADDRESS }}
        username: ${{ secrets.USERNAME }}
        passowrd: ${{ secrets.PASSWORD }}
        name: server_build_files
        path: backend/dist

