name: Deploy develop

on: 
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  API_URL: ${{ vars.API_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.1.3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd client && npm ci

      - name: Install global dependencies
        run: npm ci

      - name: Build project
        run: |
          echo ${{ env.API_URL }}
          npm run build
        env:
          CI: ""

      - name: Make tar archive
        run: tar -cf studio-crm.tar.gz ./

      - name: Write key to file
        run: | 
          echo "${{ secrets.SSH_KEY }}" > ~/key
          chmod 400 ~/key

      - name: Transfer files with scp
        run: scp -rBC -i ~/key -o StrictHostKeyChecking=no $(pwd)/studio-crm.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PROJECT_FOLDER}}

      - name: Unzip archive & remove archive
        run: ssh -i ~/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'tar -xf ${{ secrets.PROJECT_FOLDER }}/studio-crm.tar.gz -C ${{ secrets.PROJECT_FOLDER }}/ && rm ${{ secrets.PROJECT_FOLDER }}/studio-crm.tar.gz'

      - name: Restart backend service
        run: ssh -i ~/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart crm-backend'

      - name: Remove key
        run: rm ~/key
  
